kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-pv-volume  # Sets PV's name
  labels:
    type: local  # Sets PV's type to local
    app: redis
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi # Sets PV Volume
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/SOME/PATH/TO/FOLDER"
