apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pv-claim  # Sets name of PVC
  labels:
    app: redis
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany  # Sets read and write access
  resources:
    requests:
      storage: 5Gi  # Sets volume size